#!/bin/bash
# Manual Testing Guide for Warmup Fix
# Run this to verify the fix works as expected

echo "=========================================================================="
echo "Manual Testing Guide: Indicator Warmup Fix"
echo "=========================================================================="
echo ""
echo "This guide helps you manually verify that the indicator warmup warnings"
echo "have been fixed and logs are now clean."
echo ""
echo "=========================================================================="
echo "Step 1: Check current branch"
echo "=========================================================================="
git branch --show-current
echo ""
echo "Expected: copilot/fix-noisy-indicator-warnings"
echo ""

echo "=========================================================================="
echo "Step 2: Run the paper engine"
echo "=========================================================================="
echo ""
echo "Run one of the following commands:"
echo ""
echo "  # For FNO paper engine:"
echo "  python -m scripts.run_session --mode paper --config configs/dev.yaml --layout multi"
echo ""
echo "  # For equity paper engine:"
echo "  python -m engine.equity_paper_engine"
echo ""
echo "  # For options paper engine:"
echo "  python -m engine.options_paper_engine"
echo ""
echo "=========================================================================="
echo "Step 3: What to observe in the logs"
echo "=========================================================================="
echo ""
echo "BEFORE the fix (old behavior):"
echo "  ❌ WARNING: Indicator calculation error: Series must have at least 50 values, got 45"
echo "  ❌ WARNING: Indicator calculation error: Series must have at least 50 values, got 45"
echo "  ❌ ... (repeated every few seconds - hundreds of messages)"
echo ""
echo "AFTER the fix (new behavior):"
echo "  ✅ INFO: Indicator warmup: EMA(50) on NIFTY (5m) requires 50 bars, currently have 45"
echo "  ✅ (subsequent occurrences are silent - no more logs for same indicator)"
echo "  ✅ DEBUG: No underlying spots available this loop; skipping."
echo ""
echo "=========================================================================="
echo "Step 4: Verify warmup behavior"
echo "=========================================================================="
echo ""
echo "1. Start the engine and watch the first 5 minutes"
echo "2. You should see a few INFO messages about indicator warmup"
echo "3. Each unique (symbol, indicator, timeframe) combination logs only ONCE"
echo "4. After the first occurrence, no more warmup messages for that combination"
echo "5. Once enough bars are collected, indicators compute normally (no logs)"
echo ""
echo "Example expected log sequence:"
echo "  INFO: StrategyEngineV2 initialized with 2 strategies"
echo "  INFO: Starting paper engine for NIFTY, BANKNIFTY"
echo "  INFO: Indicator warmup: EMA(50) on NIFTY (5m) requires 50 bars, currently have 45"
echo "  INFO: Indicator warmup: EMA(100) on NIFTY (5m) requires 100 bars, currently have 45"
echo "  ... (engine continues running, no more warmup logs for NIFTY 5m)"
echo "  INFO: Indicator warmup: EMA(50) on BANKNIFTY (5m) requires 50 bars, currently have 48"
echo "  ... (after ~10 minutes, all indicators warmed up, no more warmup logs)"
echo ""
echo "=========================================================================="
echo "Step 5: Check log files"
echo "=========================================================================="
echo ""
echo "Log files are typically in:"
echo "  artifacts/logs/fno_paper.log"
echo "  artifacts/logs/equity_paper.log"
echo "  artifacts/logs/options_paper.log"
echo ""
echo "You can grep for indicator messages:"
echo "  grep -i 'indicator' artifacts/logs/*.log | head -20"
echo ""
echo "Expected results:"
echo "  - Only a few 'Indicator warmup' messages (one per unique combination)"
echo "  - No repeated WARNING messages about insufficient data"
echo "  - Log files are much cleaner and easier to read"
echo ""
echo "=========================================================================="
echo "Step 6: Verify no errors"
echo "=========================================================================="
echo ""
echo "While the engine is running, verify:"
echo "  1. Engine starts successfully"
echo "  2. No unhandled exceptions"
echo "  3. Indicators compute correctly once data is available"
echo "  4. Trading signals are generated normally"
echo "  5. No WARNING logs during normal warmup"
echo ""
echo "You can check for errors:"
echo "  grep -i 'error\\|exception' artifacts/logs/*.log"
echo ""
echo "Expected: Only errors unrelated to indicator warmup (if any)"
echo ""
echo "=========================================================================="
echo "Additional Validation"
echo "=========================================================================="
echo ""
echo "Run the automated warmup behavior test:"
echo "  python tests/test_warmup_behavior.py"
echo ""
echo "This will show you the exact behavior in a controlled environment."
echo ""
echo "=========================================================================="
echo "Success Criteria"
echo "=========================================================================="
echo ""
echo "✅ No repeated WARNING messages about insufficient indicator data"
echo "✅ Only one INFO message per (symbol, indicator, timeframe)"
echo "✅ Logs are clean and readable"
echo "✅ Engine runs without crashes"
echo "✅ Indicators compute correctly once data is sufficient"
echo "✅ Trading continues normally"
echo ""
echo "=========================================================================="
echo "Questions or Issues?"
echo "=========================================================================="
echo ""
echo "If you see any unexpected behavior:"
echo "  1. Check that you're on the correct branch"
echo "  2. Verify all dependencies are installed (pip install -r requirements.txt)"
echo "  3. Check the log files for any actual errors"
echo "  4. Run the test suite: python tests/test_indicators.py"
echo ""
echo "For more details, see: WARMUP_FIX_SUMMARY.md"
echo ""
